### ISSUE TITLE
Not able to add more than one customCapabilities provider.

### ISSUE THREAD

**Issue by Pranavm** [paypal/SeLion#328] opened 2016-10-03 06:16 UTC
### SeLion Version

1.1.0
### Component

SeLion-Client
### Expected Behavior

Selion provides option to add one or more custom capability provider to set capabilities for the driver instance to be created. If more than one custom capability provider is present they should be separated by commas 
### Actual Behavior

When more than once custome Capability provider is passed with classnames separated by commas, only the first class is used. The rest are ignored
### Steps to Reproduce

Create two custome capabilty providers, (classes that extend DefaultCapabilitiesBuilder) Pass the classnames separated by commas as the value of the SELENIUM_CUSTOM_CAPABILITIES_PROVIDER property.

**Comment by mach6** [comment] 2016-10-03 17:20
@Pranavm thanks for finding this. Fyi, I have a pending fix in progress here - https://github.com/mach6/SeLion/commit/e59fbc2e9ad6fa4a1ed6a883b6dfcf80ee749860

**Comment by mach6** [comment] 2016-10-03 17:22
Note: The root cause of this issue also impacts configuring >1 SeLion event listeners and >1 element event listeners

**Comment by mach6** [comment] 2016-10-19 21:29
fixed with https://github.com/paypal/SeLion/commit/bccb9c85f0a11088c59829b11da7d39560df41d1

**Closed as completed by mach6** 2016-10-19 21:29 UTC
Labels: bug, component: client
